apiVersion: v1
kind: Service
metadata:
  name: kubernetes-api-client
  labels:
    app: kubernetes-tp
spec:
  ports:
    - port: 3000
  selector:
    app: kubernetes-tp
    partie: kubernetes-api-client
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-api-client
  labels:
    app: kubernetes-tp
spec:
  template:
    spec:
      containers:
        - name: kubernetes-api-client
          image: pfourny/kubernetes-tp-api-client:latest
          ports:
            - containerPort: 3000
          readinessProbe:
            failureThreshold: 5 # Reessayer 5 fois
            httpGet:
              path: /ping
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 30 # Attendre 30s avant de tester
            periodSeconds: 10 # Attendre 10s entre chaque essai
            timeoutSeconds: 5 # Attendre 5s la reponse
    metadata:
      labels:
        app: kubernetes-tp
        partie: kubernetes-api-client
  selector:
    matchLabels:
      app: kubernetes-tp
      partie: kubernetes-api-client
  strategy:
    type: Recreate
  replicas: 1
