apiVersion: v1
kind: Service
metadata:
  name: database
  labels:
    app: kubernetes-tp
spec:
  ports:
    - port: 3306
  selector:
    app: kubernetes-tp
    partie: database
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  labels:
    app: kubernetes-tp
spec:
  template:
    spec:
      containers:
        - image: mariadb:latest
          name: database
          ports:
            - containerPort: 3306
          env:
            - name: MARIADB_ROOT_PASSWORD
              value: root
    metadata:
      labels:
        app: kubernetes-tp
        partie: database
  selector:
    matchLabels:
      app: kubernetes-tp
      partie: database
  strategy:
    type: Recreate
  replicas: 1
