apiVersion: v1
kind: Service
metadata:
  name: kubernetes-front
  labels:
    app: kubernetes-tp
spec:
  ports:
    - port: 5173
  selector:
    app: kubernetes-tp
    partie: kubernetes-front
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-front
  labels:
    app: kubernetes-tp
spec:
  template:
    spec:
      containers:
        - name: kubernetes-front
          image: pfourny/kubernetes-tp-front:latest
          ports:
            - containerPort: 5173
          env:
            - name: VITE_API_IMAGE_URL
              value: "http://127.0.0.1:3001/image"
            - name: VITE_API_TEXT_URL
              value: "http://127.0.0.1:3002/text"
            - name: VITE_API_CLIENT_URL
              value: "http://127.0.0.1:3000/create/container"
          readinessProbe:
            failureThreshold: 5 # Reessayer 5 fois
            httpGet:
              path: /
              port: 5173
              scheme: HTTP
            initialDelaySeconds: 30 # Attendre 30s avant de tester
            periodSeconds: 10 # Attendre 10s entre chaque essai
            timeoutSeconds: 5 # Attendre 5s la reponse
    metadata:
      labels:
        app: kubernetes-tp
        partie: kubernetes-front
  selector:
    matchLabels:
      app: kubernetes-tp
      partie: kubernetes-front
  strategy:
    type: Recreate
  replicas: 1
