// Code generated by ent, DO NOT EDIT.

package text

const (
	// Label holds the string label denoting the text type in the database.
	Label = "text"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldText holds the string denoting the text field in the database.
	FieldText = "text"
	// Table holds the table name of the text in the database.
	Table = "texts"
)

// Columns holds all SQL columns for text fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldText,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
)
