// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"

	"github.com/FournyP/kubernetes-tp/apis/text/ent/migrate"

	"github.com/FournyP/kubernetes-tp/apis/text/ent/text"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Text is the client for interacting with the Text builders.
	Text *TextClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Text = NewTextClient(c.config)
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:    ctx,
		config: cfg,
		Text:   NewTextClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:    ctx,
		config: cfg,
		Text:   NewTextClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Text.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Text.Use(hooks...)
}

// TextClient is a client for the Text schema.
type TextClient struct {
	config
}

// NewTextClient returns a client for the Text from the given config.
func NewTextClient(c config) *TextClient {
	return &TextClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `text.Hooks(f(g(h())))`.
func (c *TextClient) Use(hooks ...Hook) {
	c.hooks.Text = append(c.hooks.Text, hooks...)
}

// Create returns a builder for creating a Text entity.
func (c *TextClient) Create() *TextCreate {
	mutation := newTextMutation(c.config, OpCreate)
	return &TextCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Text entities.
func (c *TextClient) CreateBulk(builders ...*TextCreate) *TextCreateBulk {
	return &TextCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Text.
func (c *TextClient) Update() *TextUpdate {
	mutation := newTextMutation(c.config, OpUpdate)
	return &TextUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TextClient) UpdateOne(t *Text) *TextUpdateOne {
	mutation := newTextMutation(c.config, OpUpdateOne, withText(t))
	return &TextUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TextClient) UpdateOneID(id int) *TextUpdateOne {
	mutation := newTextMutation(c.config, OpUpdateOne, withTextID(id))
	return &TextUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Text.
func (c *TextClient) Delete() *TextDelete {
	mutation := newTextMutation(c.config, OpDelete)
	return &TextDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TextClient) DeleteOne(t *Text) *TextDeleteOne {
	return c.DeleteOneID(t.ID)
}

// DeleteOne returns a builder for deleting the given entity by its id.
func (c *TextClient) DeleteOneID(id int) *TextDeleteOne {
	builder := c.Delete().Where(text.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TextDeleteOne{builder}
}

// Query returns a query builder for Text.
func (c *TextClient) Query() *TextQuery {
	return &TextQuery{
		config: c.config,
	}
}

// Get returns a Text entity by its id.
func (c *TextClient) Get(ctx context.Context, id int) (*Text, error) {
	return c.Query().Where(text.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TextClient) GetX(ctx context.Context, id int) *Text {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *TextClient) Hooks() []Hook {
	return c.hooks.Text
}
