// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// TextsColumns holds the columns for the "texts" table.
	TextsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "text", Type: field.TypeString},
	}
	// TextsTable holds the schema information for the "texts" table.
	TextsTable = &schema.Table{
		Name:       "texts",
		Columns:    TextsColumns,
		PrimaryKey: []*schema.Column{TextsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		TextsTable,
	}
)

func init() {
}
