// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/FournyP/kubernetes-tp/ent/schema"
	"github.com/FournyP/kubernetes-tp/ent/text"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	textFields := schema.Text{}.Fields()
	_ = textFields
	// textDescName is the schema descriptor for name field.
	textDescName := textFields[0].Descriptor()
	// text.DefaultName holds the default value on creation for the name field.
	text.DefaultName = textDescName.Default.(string)
}
