name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push front
      uses: docker/build-push-action@v3
      with:
        context: ./front/
        push: true
        tags: FournyP/kubernetes-tp-front:latest
    - name: Build and push api text
      uses: docker/build-push-action@v3
      with:
        context: ./apis/text/
        push: true
        tags: FournyP/kubernetes-tp-api-text:latest
    - name: Build and push api image
      uses: docker/build-push-action@v3
      with:
        context: ./apis/image/
        push: true
        tags: FournyP/kubernetes-tp-api-image:latest
    - name: Build and push api client
      uses: docker/build-push-action@v3
      with:
        context: ./apis/client/
        push: true
        tags: FournyP/kubernetes-tp-api-client:latest
